### ISSUE TITLE
Port gendb.py to python3

### ISSUE THREAD

**Issue by 0xfabi** [svdhoog/FLAViz#10]
1. The porting of gendb.py to python3 did not yet work correctly.
I ran the old gendb.py using python2 on the same XML files to check this.
Error output:

Traceback (most recent call last):
  File "gendb.py", line 263, in <module>
    load_iteration_file(i, itsdir, db)
  File "gendb.py", line 108, in load_iteration_file
    db.execute( get_agent_sql(data) ) # store data in db
sqlite3.OperationalError: near "minsky_state_40": syntax error
The variable minsky_state_40 is well-defined in the model.xml, as well as outputted in the 20.xml file.

2. Please also port gendb_special.py to python3 (probably best to first fix gendb.py, and then do a diff with the gendb_special.py, since the changes are minimal).

**Comment by 0xfabi** [comment]
@svdhoog : Can you tell me how you executed it? Then I can reproduce the error.

**Comment by svdhoog** [comment]
@0xfabi OK, I have put the model code (model.xml files) and the XML files in the GitLab repo ETACE-Conquaire. So you first have to clone that one. The relevant folders are:

- Model code: `ETACE-Conquaire/model_code/Financial_Fragility_Network_Model_2.0`
- Xml data: `ETACE-Conquaire/ETACE-Conquaire/Final_format/data/gamma_scenarios/xml/set_1/run_1`

The command to run is from the folder `FLAViz/src/data_conversion_scripts/xml_db` (replace `path-to-gitlab` with your full path):
```
python3 gendb.py /path-to-gitlab/ETACE-Conquaire/model_code/Financial_Fragility_Network_Model_2.0/eurace_model.xml /path-to-gitlab/ETACE-Conquaire/Final_format/data/gamma_scenarios/xml/set_1/run_1
```
Note that this will create an output file called `iters.db` in the folder of the gendb.py script. 

2. It would also be good to add an optional parameter to `gen_db.py` and `gendb_special.py` for setting the output path:
```
-o output folder; optional. By default, output is written to the same folder as where the script is.
```

**Comment by svdhoog** [comment]
Actually, the error occurs at a random variable. You can repeat multiple times and each time it stops at a different variable, so could have smth to do with buffer sizes? You can also try `set_2/run_1` or `set_2/run_2`.

**Comment by 0xfabi** [comment]
All errors should be fixed and everything was ported to python3.

**Comment by 0xfabi** [comment]
Added check if folder exists for outputpath.
