### ISSUE TITLE
db_hdf5_v2.py shows warning about pandas.lib being deprecated

### ISSUE THREAD

**Issue by svdhoog** [svdhoog/FLAViz#11]
```
db_hdf5_v2.py:41: FutureWarning: pandas.lib is deprecated and will be removed in a future version.
You can access infer_dtype as pandas.api.types.infer_dtype
  types = df.apply(lambda x: pd.lib.infer_dtype(x.values))
```

**Comment by 0xfabi** [comment]
It seems like we have to change 'pd.lib.infer_dtype(x.values)' to 'pd.api.types.infer_dtype(x.values)' [see https://pandas.pydata.org/pandas-docs/stable/generated/pandas.api.types.infer_dtype.html].

Can you tell me how you execute it? Then I can test my guess and see if the warning is gone.

**Comment by svdhoog** [comment]
```
python3 /path/db_hdf5_v2.py -o h5/ -v -s db/
```
where `db/` is the folder with several files called `set_n_run_k_iters.db` (can also be just one).
The folder `h5/` will be created by the script if it does not exist yet. If all these paths can be absolute I do not know, I use the relative paths to `db/` and `h5/` by starting from a folder in which those are subfolders. I do give the absolute path to `db_hdf5_v2.py` though.

**Comment by 0xfabi** [comment]
Where can I find this db/ folder with the set...iters.db files?

**Comment by svdhoog** [comment]
https://gitlab.ub.uni-bielefeld.de/hoog/ETACE-Conquaire/tree/master/Final_format/data/gamma_scenarios/db

**Comment by 0xfabi** [comment]
Ok, I have updated the lib use and also fixed some path showing problems. ("Directory [path] is used for output files") and now shows correct output path.

**Comment by svdhoog** [comment]
Was this last update committed? Can't find it in commits, and pull your fork still gives me this error.

**Comment by 0xfabi** [comment]
Should be commited now.
