### ISSUE TITLE
merge_hdf_agentwise.py

### ISSUE THREAD

**Issue by svdhoog** [svdhoog/FLAViz#14]
- [] to be fixed with correct output folder
- to work from other folder than location of script itself

**Comment by svdhoog** [comment]
**Note** I was unable to replicate the error with the folder `gent` being created if I set the output folder inside the input folder with the h5 files. If this error still appears, we should record the steps to replicate it.

1 Current output:

   - Directory [output] was created and is used for output files

Should be: full path of output folder.

2 When no output folder is specified, the output is:

   - Directory [output_test] was created and is used for output files

I could not find out where this folder is located (!)

**Steps to replicate:**

- Use the test data in the GitLab repo `ETACE-Conquaire`:

    ETACE-Conquaire/Final_format/data/gamma_scenarios/h5/

This should contain files `set_*_run_*_iters.h5`.
Direct link: https://gitlab.ub.uni-bielefeld.de/hoog/ETACE-Conquaire/tree/master/Final_format/data/gamma_scenarios/h5

- In the scripts folder `hdf_agentwise` prepare a plain text file called `agentlist.txt` with agent names to convert:

    Eurostat
    Firm

- Run script `merge_hdf_agentwise.py` from any folder by setting these environment variables:

    FULL_PATH_TO_SCRIPT='/home/svdhoog/files-server/GIT/GitHub/FLAViz@0xfabi/ETACE/src/data_conversion_scripts/hdf_agentwise/'

    OUTPATH='/home/svdhoog/files-server/GIT/GitHub/FLAViz@0xfabi/ETACE/data/output'

    HDFPATH='/home/svdhoog/files-server/GIT/GitLab/Etace-Conquaire-Git/ETACE-Conquaire/Final_format/data/gamma_scenarios/h5/'

    agentlist='/home/svdhoog/files-server/GIT/GitHub/FLAViz@0xfabi/ETACE/src/data_conversion_scripts/hdf_agentwise/agentlist.txt'

- Run the script:

    python3 $FULL_PATH_TO_SCRIPT/merge_hdf_agentwise.py -o $OUTPATH -vs $HDFPATH $agentlist

**Comment by svdhoog** [comment]
Points 1-2 still to be corrected using full path. Actual error with the folder `gent` being created is a separate issue having to do with recursive folders, see #23.

**Comment by 0xfabi** [comment]
Point 1 and 2 should be fixed. 
If you do not set an output path there is an output folder created in root directory of FLAViz, e.g. /path/to/FLAViz/output/ which contains the h5 files.

**Comment by svdhoog** [comment]
Checked:
- Point 1 is fixed. Full path is displayed.
- Point 2 is not yet fixed, example output is like this:

> Directory [/home/svdhoog/backup/Big_Archive_of_Everything/Estimation_and_Calibration/Data/calibration-mode-3-K2/output_input]

The full path is the location of the script `merge_hdf_agentwise.py`. So it currently appends "output_" before the name of the `input` folder, and re-uses the full path where the script is executed from.
Should be: output folder next to input folder, without the "_input"

**Comment by svdhoog** [comment]
# Current default:
- If no outpath is provided: output is written to folder `merged_agent_wise` in parent folder of input path.
