### ISSUE TITLE
Summarystats.py, docs/visualisation_scripts/config.rst: use of incorrect terms quartiles, should be percentiles, or quantiles

### ISSUE THREAD

**Issue by svdhoog** [svdhoog/FLAViz#18]
1 Online documentation: `docs/visualisation_scripts/config.rst`

In the last example for config.yaml, just before the explanation of plot_config.yaml, test 2 uses the settings:

```
    plot2:
        timeseries:
            agent: Firm
            analysis: multiple_run
            variables:
                var1: [price]
            set: [10]
            run: [1]
            major: [range,[6020,12500,20]]
            minor: [range,[1,80]]
            summary: custom_quantile
            quantile_values:
               lower_quartile : 0.20
               upper_quartile : 0.80
```

Here the terms ``lower_quartile`` and ``upper_quartile`` would be technically incorrect and should be renamed to ``lower_quantile`` and  ``upper_quantile`` (100-based), or even better: ``lower_percentile`` and  ``upper_percentile`` . 

- Also check the description in Manual.pdf for Summarystats.py for this: It should use lower/upper quantile.

- Added values ``no``, ``quantile`` and ``full``: it seems that `summary: no` is a valid value? Is this in the code? Also ``quantile`` was not in the documentation, but it is in the code, and it works?

- Possible values : ``no``, ``mean``, ``median``, ``quantile``, ``custom_quantile``, ``upper_quartile``, ``lower_quartile``, ``maximum``, ``minimum``, ``full``.

- The documentation should explain what the values mean:

```
no : no summary
...
quantile: returns the specified quantile of the data
full : returns the entire data ensemble
```
2 In ``plot_config.yaml``, the plot setting ``fill_between_quartiles`` should be renamed  ``fill_between_quantiles``.

**Comment by 0xfabi** [comment]
1. I have renamed lower_quartile/upper_quartile to lower_percentile/upper_percentile.

summary types which have an effect: mean, median, upper_percentile, lower_percentile, custom_quantile, minimum, maximum, full
summary: no is not a possible value.

2. I have renamed to 'fill_between'. You can use this parameter moreover for filling the bars from a histogram.

In addition I have updated the docs readme files.

**Comment by svdhoog** [comment]
The change in quantile_values was correct (but quantile would also be correct here, just more general):

```
quantile_values:
-               lower_quantile : 0.20
-               upper_quantile : 0.80
+               lower_percentile : 0.20
+               upper_percentile : 0.80
```

But the changes of lower- and upper- `quartile` to lower- and upper- `percentile` were incorrect, see  the comments in the commit. Those values are at the same level as `quantile_values`.

Terminology:
- quantiles are any points at which a subinterval starts, for any subdivision of the [0,1] interval
- percentiles are the points that subdivide [0,1] into 99 sub-intervals
- quartiles are the points at the 25, 50, 75 percentiles

**Comment by 0xfabi** [comment]
Please check if I understood you right now and renamed everything correct.

**Comment by svdhoog** [comment]
All correct.
