### ISSUE TITLE
Citation DOI?

### ISSUE THREAD

**Issue by svaksha** [svdhoog/FLAViz#21]
How can one cite this software repo - is there a DOI for this repo? would be useful to have it on the main README.md page. Thanks.

**Comment by svdhoog** [comment]
I would say for now, cite it using the GitHub URL?
I could make a data publication on PUB, but the only content there would be the URL to the GitHub repo.
Or does it make sense to zip it up and copy it there, perhaps together with the manual PDF? That would make the PUB the distribution channel for releases, while the GitHub repo would be the development channel. Fine by me, but I would not have access to PUB forever.

**Comment by svaksha** [comment]
On Mon, May 28, 2018 at 8:34 AM, svdhoog <notifications@github.com> wrote:
>
> I would say for now, cite it using the GitHub URL?

True.

> I could make a data publication on PUB, but the only content there would be the URL to the GitHub repo.
> Or does it make sense to zip it up and copy it there, perhaps together with the manual PDF? That would make the PUB the distribution channel for releases, while the GitHub repo would be the development channel. Fine by me, but I would not have access to PUB forever.
>

Currently, if you zip the repo and upload to PUB, the will be no
versioning and a user will not be aware of changes in the github repo,
so its better to cite the github url.  Not sure I understood why
access to PUB matters - AFAIK, an assigned DOI cannot be reused or
changed, so if the software changes it needs a new DOI.

**Comment by svdhoog** [comment]
Right. That's why the PUB is not a good channel for software releases. Only reason to use PUB was to get a DOI. But why would anyone want a DOI for software?? It's never finished, never fully bug-free.

**Comment by svdhoog** [comment]
... and did I mention PUB-login will not be accessible for non-uni employees?

**Comment by svdhoog** [comment]
Solution is to cite the GitHub URL to the Repo.
