### ISSUE TITLE
Bug: merge_hdf_agentwise.py using recursive folders

### ISSUE THREAD

**Issue by svdhoog** [svdhoog/FLAViz#23]
By default merge_hdf_agentwise.py traverses a folder hierarchy and processes files called set_*_run_*.h5 in each subfolder, and then produces the agent-wise h5 files (urostat.h5, Bank.h5 etc) in a parallel folder structure in the output folder. But due to a bug in parsing the folder names, possibly related to /, this malfunctions. See screenshot at end.

Input folder:

`h5/combined`

Output should be in:

`h5_agentwise/combined`

But instead, two folders are created:

`h5_agentwise`
`h5_agentwiseombined`

And the output appears in:

`h5_agentwiseombined` [ommiting the /c from the path]

Probably just escaping the slash should help.

Note: the `/c` is not a special character, renaming the folder to something other like `um` also causes the error (I assumed `/u` is also not special either).

![screenshot](https://user-images.githubusercontent.com/11057058/40664717-e03b0482-635b-11e8-9a53-0893df478679.png)

**Comment by 0xfabi** [comment]
The bug should be fixed now.

**Comment by svdhoog** [comment]
Tested correctly.
