### ISSUE TITLE
Warning about kwarg being deprecated

### ISSUE THREAD

**Issue by svdhoog** [svdhoog/FLAViz#26]
This is probably not something we do, but in a module we call?:

```
/usr/local/lib/python3.4/dist-packages/matplotlib/axes/_axes.py:6462:` UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
  warnings.warn("The 'normed' kwarg is deprecated, and has been "
```

**Comment by 0xfabi** [comment]
https://github.com/mwaskom/seaborn/issues/1392

It seems like this issue was fixed but there is no stable release until now. 
But it should be released soon.

**Comment by svdhoog** [comment]
Temporary solution already provided by russtoku:

> Sorry, but it appears that the seaborn 0.8.1 package from conda 4.5.0 is lacking this patch. In line 214 of seaborn/distributions.py, I changed "normed" to "norm_hist" and the warning message is gone. Thanks!
