### ISSUE TITLE
FLAViz main.py has no help -h parameter, no verbose mode

### ISSUE THREAD

**Issue by svdhoog** [svdhoog/FLAViz#5]
TODO in file: src/visualisation_scripts/main.py
- add -h output, listing usage
- add verbose -v output, tracking steps and progress
- possible python2 -> python3 porting issues: (e.g print)

**Comment by 0xfabi** [comment]
There is still a -h option. It gives you the following feedback:

shell$ python3 main.py -h
usage: main.py [-h] --parameterpath PARAMETERPATH [--verbose VERBOSE]

Visualise and transform various time-series data.

optional arguments:
  -h, --help            show this help message and exit
  --parameterpath PARAMETERPATH, -p PARAMETERPATH
                        Path to folder containing the parameter (.yaml) files
  --verbose VERBOSE, -v VERBOSE
                        Activate the verbose mode which contains tracking
                        steps and progress



What do you mean with tracking steps and progress? Right now you get some feedback about which plots are created.


We should not support python2 because the code depends on python3.

**Comment by svdhoog** [comment]
OK, true, my installation gave an error cause I did not have python3-yaml package installed.
I added some python3 packages to the dependencies.

**Comment by svdhoog** [comment]
I would say that `parameter` should be replaced by`configuration` everywhere. I mean in the help, not in the entire code base...

**Comment by 0xfabi** [comment]
I have changed the parameter path to configpath and updated the documentation. Should I also change parameters.py to configuration.py?

Also I've implemented a progress bar for verbose mode. You just have to use -v to execute it.

Example:
shell$ python3 main.py -h -v

Preprocessing 1: [################                                  ] 33%
  Preprocessing 1: [##################################                ] 67%
  Preprocessing 1: [##################################################] 100%
  Preprocessing 2: [################                                  ] 33%
  Preprocessing 2: [##################################                ] 67%
  Preprocessing 2: [##################################################] 100%
- Directory [results] is used for output files
- Directory [timeseries] is used for output files
  Visualisation: [####                                              ] 8%
- Directory [results] is used for output files
- Directory [timeseries] is used for output files
  Visualisation: [########                                          ] 17%
- Directory [results] is used for output files
- Directory [timeseries] is used for output files
  Visualisation: [############                                      ] 25%
- Directory [results] is used for output files
- Directory [timeseries] is used for output files
  Visualisation: [################                                  ] 33%
- Directory [results] is used for output files
- Directory [boxplot] is used for output files
  Visualisation: [#####################                             ] 42%
- Directory [results] is used for output files
- Directory [scatterplot] is used for output files
  Visualisation: [#########################                         ] 50%
- Directory [results] is used for output files
- Directory [scatterplot] is used for output files
  Visualisation: [#############################                     ] 58%
- Directory [results] is used for output files
- Directory [scatterplot] is used for output files
  Visualisation: [##################################                ] 67%
- Directory [results] is used for output files
- Directory [histogram] is used for output files
  Visualisation: [######################################            ] 75%
- Directory [results] is used for output files
- Directory [histogram] is used for output files
  Visualisation: [##########################################        ] 83%
- Directory [results] is used for output files
- Directory [histogram] is used for output files
  Visualisation: [##############################################    ] 92%
- Directory [results] is used for output files
- Directory [histogram] is used for output files
  Visualisation: [##################################################] 100%

**Comment by svdhoog** [comment]
OK great! RE: "Should I also change parameters.py to configuration.py?" No, let's keep it like it is.

**Comment by svdhoog** [comment]
Update the progress bar on same line using \r

**Comment by 0xfabi** [comment]
I can offer you the following: 

/FLAViz_root$ python3 src/visualisation_scripts/main.py -p src/visualisation_scripts/config/ -v

Step1: Preparing data structure [##############################] 100%
Step2: Processing data file [##############################] 100%
Step3: Filtering the data [##############################] 100%
\- Directory [results] is used for output files
\- Directory [timeseries] is used for output files
Step3: Filtering the data [##############################] 100%
\- Directory [results] is used for output files
\- Directory [timeseries] is used for output files
Step3: Filtering the data [##############################] 100%
\- Directory [results] is used for output files
\- Directory [timeseries] is used for output files
Step3: Filtering the data [##############################] 100%
\- Directory [results] is used for output files
\- Directory [timeseries] is used for output files
Step3: Filtering the data [##############################] 100%
\- Directory [results] is used for output files
\- Directory [boxplot] is used for output files
Step3: Filtering the data [##############################] 100%
\- Directory [results] is used for output files
\- Directory [scatterplot] is used for output files
Step3: Filtering the data [##############################] 100%
\- Directory [results] is used for output files
\- Directory [scatterplot] is used for output files
Step3: Filtering the data [##############################] 100%
\- Directory [results] is used for output files
\- Directory [scatterplot] is used for output files
Step3: Filtering the data [##############################] 100%
\- Directory [results] is used for output files
\- Directory [histogram] is used for output files
Step3: Filtering the data [##############################] 100%
\- Directory [results] is used for output files
\- Directory [histogram] is used for output files
Step3: Filtering the data [##############################] 100%
\- Directory [results] is used for output files
\- Directory [histogram] is used for output files
Step3: Filtering the data [##############################] 100%
\- Directory [results] is used for output files
\- Directory [histogram] is used for output files
Step4: Visualisation [##############################] 100%

**Comment by svdhoog** [comment]
1. Align the start of the progress bars
2. Change: `Step3: Filtering the data` to
`Step3: Filtering the data for: plot_key` where plot_key are the key used in plot_config.yaml

**Comment by 0xfabi** [comment]
I've done these changes.

**Comment by svdhoog** [comment]
- During step 3, already step 4 starts, so rename Filtering/Plotting

**Comment by 0xfabi** [comment]
Done.
