### ISSUE TITLE
Color pallet randomly chosen

### ISSUE THREAD

**Issue by svdhoog** [svdhoog/FLAViz#9]
Repeating the plotting process with the out-of-box test data twice yields plots with different colors.
This is due to the randomly chosen color pallet for multi-line plots, or eve for the boundaries of the quantile plots.

![flaviz-plots-colors](https://user-images.githubusercontent.com/11057058/39767369-de4d347c-52e6-11e8-9ceb-e4a11d3eae40.png)

TODO: Fix the color pallet.

**Comment by 0xfabi** [comment]
Fixed random colors. 
If you prefer other colors, we could make use of the one of the following colormaps: https://matplotlib.org/examples/color/colormaps_reference.html

**Comment by svdhoog** [comment]
Add option to plot_config.yaml: 
```
self.linecolor=[true|false]
if(self.linecolor) cm.rainbow
else cm.greyscale
```

**Comment by 0xfabi** [comment]
Added greyscale support.

**Comment by 0xfabi** [comment]
Boxplot needs a color support. Add colormap to box plot.

**Comment by 0xfabi** [comment]
Boxplots now also can be plotted as greyscaled plots.
